### ISSUE TITLE
Fix substitution of data for oneOf-fields

### ISSUE THREAD

**Issue by irrbd** [VitaliyMatveev/reagent-js#101]
**How reproduce the bug**
1. Choose some field into an oneOf-field. You can see our substituted data.
2. Choose another field into the oneOf-field. You can see our another substituted data.
3. Return on the first field. Our substituted data disappeared.

[Video_with_the_error.zip](https://github.com/VitaliyMatveev/reagent-js/files/2648240/Video_with_the_error.zip)

**Comment by irrbd** [comment]
In this case we have same key-names into oneOf-objects:
```
{
  type: 'object',
  title: 'Способ предоставления результата оказания услуги',
  oneOfFieldName: 'issue_method',
  oneOfFieldTitle: 'Способ предоставления результата оказания услуги',
  oneOf: [
    {
      type: 'object',
      title: 'По электронной почте',
      id: 'Email',
      properties: {
        issue_place_id: {
          title: 'Адрес электронной почты',
          type: 'string',
        },
      },
      required: ['issue_place_id'],
    },
    {
      type: 'object',
      title: 'МФЦ',
      id: 'MFC',
      properties: {
        issue_place_id: {
          title: 'Офис МФЦ',
          type: 'radio',
          items: mfcOffices,
        },
      },
      required: ['issue_place_id'],
    },
  ],
}
```

In this case we don't use auto substitution from the property value from <Form />.
And we use resulting `issue_method` and `issue_place_id` from data as special attributes of a case.

**The problem:**
If we fill the second radio-field, then check at the first email-input,
we have the value from the second field into the first input (a some `id`, `64` for example, in our case).

**Comment by VitaliyMatveev** [comment]
The most reasonable solution in this case is change scheme to 
```oneOf: [
    {
      type: 'object',
      title: 'По электронной почте',
      id: 'Email',
      properties: {
        email: {
          title: 'Адрес электронной почты',
          type: 'string',
        },
      },
      required: ['email'],
    },
    {
      type: 'object',
      title: 'МФЦ',
      id: 'MFC',
      properties: {
        office_id: {
          title: 'Офис МФЦ',
          type: 'radio',
          items: mfcOffices,
        },
      },
      required: ['office_id'],
    },
  ],```
and handle result
