### ISSUE TITLE
Can not use number as a key within schema

### ISSUE THREAD

**Issue by SlavaStartsev** [VitaliyMatveev/reagent-js#58]
**Problem** Form ignores all changes if key is a number(letters and digits is fine tho). Error below falls to console.
![screenshot from 2018-07-13 16 19 16](https://user-images.githubusercontent.com/22825777/42693733-c25f9cf4-86b8-11e8-9131-811ff76ed5ee.png)
**Expect** Fix(numeric key must be a valid one).
This schema might help:
```javascript
{
  type: 'object',
  properties: {
    123: {
      type: 'string',
      title: 'some title',
    },
  },
}
```

**Comment by VitaliyMatveev** [comment]
I recommend use prefix for this case
